version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker: # run the steps with Docker
    - image: circleci/ruby:2.6.3-node-browsers
      environment: # environment variables for primary container
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: circleci-demo-ruby
        RAILS_ENV: test
    - image: circleci/postgres:9.5-alpine # database image
      environment: # environment variables for database
        POSTGRES_USER: circleci-demo-ruby
        POSTGRES_DB: boise_movies_test
        POSTGRES_PASSWORD: ""
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  backend-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: gem install bundler

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - boise-movies-bundle-v2-{{ checksum "Gemfile.lock" }}
            - boise-movies-bundle-v2-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: boise-movies-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - boise-movies-yarn-{{ checksum "yarn.lock" }}
            - boise-movies-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: boise-movies-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results
      - run:
          name: Stash Coverage Results
          command: |
            cp -R coverage/.resultset.json tmp/codeclimate.total.json
      - persist_to_workspace:
          root: .
          paths:
            - tmp
  upload-coverage:
    <<: *defaults
    environment:
      - CC_TEST_REPORTER_ID: fd2970201da4508cee7c341c941ba12bf27218029ecd96cd783396290fe996c2
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: mv cc-test-reporter
          command: mv ./cc-test-reporter tmp/
      - run:
          name: ls env
          command: |
            ls -l ./tmp/
      - run:
          name: Upload coverage results to Code Climate
          command: |
            cd tmp/
            ./cc-test-reporter upload-coverage -i ./codeclimate.total.json
workflows:
  version: 2

  commit:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - upload-coverage:
          requires:
             - backend-tests