version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker: # run the steps with Docker
    - image: circleci/ruby:2.6.3-node-browsers
      environment: # environment variables for primary container
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: circleci-demo-ruby
        RAILS_ENV: test
    - image: circleci/postgres:9.5-alpine # database image
      environment: # environment variables for database
        POSTGRES_USER: circleci-demo-ruby
        POSTGRES_DB: boise_movies_test
        POSTGRES_PASSWORD: ""
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  backend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - persist_to_workspace:
          root: ~/repo/tmp
          paths:
            - codeclimate.backend.json
  upload-coverage:
    <<: *defaults
    environment:
      - CC_TEST_REPORTER_ID: fd2970201da4508cee7c341c941ba12bf27218029ecd96cd783396290fe996c2
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2

  commit:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - upload-coverage:
          requires:
             - backend-tests